# Site settings
title: Sergi Pasoev
email: s.pasoev@gmail.com
description: "A blog to accompany the Github repositories from the same user."
baseurl: ""
url: "http://pasoev.github.io"
github_username:  pasoev
highlighters: pygments
# Build settings
markdown: kramdown
permalink: pretty

