# Site settings
title: Sergo Pasoevi
email: spasoevi@gmail.com
description: "A blog to accompany the Github repositories from the same user."
baseurl: ""
url: "http://pasoevi.com"
github_username:  pasoevi
highlighters: rouge
# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: <!--more-->
collections:
  projects:
    output: true

exclude:
  - node_modules
